---
name: Gource Visualization

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate Visualization
        run: |
          ./border_template.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gource-visualization
          path: output/gource.mp4
