---
name: Build Docker Image

# yamllint disable-line rule:truthy
on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Create docker tag (from git reference)
        # A tag name may only contain lower- and uppercase letters, digits, underscores, periods and dashes.
        run: |
          echo "TAG=$(echo -n "${{ github.ref_name }}" \
            | tr --complement --squeeze-repeats '[:alnum:]._-' '_')" \
            >> "${GITHUB_ENV}"
      # Image name must only contain lowercase letters
      - run: |
          echo "IMAGE=$(echo -n "${{ github.repository }}" \
            | tr '[:upper:]' '[:lower:]' )" \
            >> "${GITHUB_ENV}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/${{ env.IMAGE }}:${{ env.TAG }}"
